openapi: 3.0.0
info:
  title: Travel Booking API
  description: API for managing travel bookings and destinations
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Local server
paths:
  /holidays:
    get:
      summary: Get all holidays
      responses:
        '200':
          description: A list of holidays
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Holiday'
    post:
      summary: Book a holiday
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingRequest'
      responses:
        '201':
          description: Successfully booked holiday
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /holidays/{holiday_id}:
    parameters:
      - name: holiday_id
        in: path
        required: true
        description: ID of the holiday to retrieve
        schema:
          type: integer
    get:
      summary: Get holiday by ID
      responses:
        '200':
          description: Details of the holiday
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Holiday'
        '404':
          description: Holiday not found
        '500':
          description: Internal Server Error
    delete:
      summary: Cancel holiday booking by ID
      responses:
        '204':
          description: Holiday booking successfully canceled
        '404':
          description: Holiday booking not found
        '500':
          description: Internal Server Error
  /destinations:
    get:
      summary: Get all destinations
      responses:
        '200':
          description: A list of destinations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Destination'
    post:
      summary: Add a new destination
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Destination'
      responses:
        '201':
          description: Successfully added destination
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Destination'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /destinations/{destination_id}:
    parameters:
      - name: destination_id
        in: path
        required: true
        description: ID of the destination to retrieve
        schema:
          type: integer
    get:
      summary: Get destination by ID
      responses:
        '200':
          description: Details of the destination
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Destination'
        '404':
          description: Destination not found
        '500':
          description: Internal Server Error
    put:
      summary: Update destination by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Destination'
      responses:
        '200':
          description: Successfully updated destination
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Destination'
        '404':
          description: Destination not found
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
    delete:
      summary: Delete destination by ID
      responses:
        '204':
          description: Destination successfully deleted
        '404':
          description: Destination not found
        '500':
          description: Internal Server Error
  /bookings:
    get:
      summary: Get all bookings
      responses:
        '200':
          description: A list of bookings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Booking'
    post:
      summary: Book a holiday
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookingRequest'
      responses:
        '201':
          description: Successfully booked holiday
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Booking'

